
# ******************************************************
#
#    NKDIO Configuration
#                           
# ******************************************************
[NP-6111-JH2]
ConfigPath = "/NP-6111-JH2/nkio_config.ini"
[NP-6111-JH2-NEW]
ConfigPath = "/NP-6111-JH2-NEW/nkio_config.ini"
[NP-6111-JH2B]
ConfigPath = "/NP-6111-JH2B/nkio_config.ini"
[NP-6111-JH3]
ConfigPath = "/NP-6111-JH3/nkio_config.ini"
[NP-6113-16I16O]
ConfigPath = "/NP-6113-16I16O/nkio_config.ini"
[NP-6113-MVS]
ConfigPath = "/NP-6113-MVS/nkio_config.ini"
[NP-6116]
ConfigPath = "/NP-6116/nkio_config.ini"
[NP-6118]
ConfigPath = "/NP-6118/nkio_config.ini"
[NP-6122-H1]
ConfigPath = "/NP-6122-H1/nkio_config.ini"
[NP-6122-H1-NEW]
ConfigPath = "/NP-6122-H1-NEW/nkio_config.ini"
[NP-6122-H1B]
ConfigPath = "/NP-6122-H1B/nkio_config.ini"
[NP-6122-H7-NEW]
ConfigPath = "/NP-6122-H7-NEW/nkio_config.ini"
[NP-6122-JH2]
ConfigPath = "/NP-6122-JH2/nkio_config.ini"
[NP-6122-JH2-NEW]
ConfigPath = "/NP-6122-JH2-NEW/nkio_config.ini"
[NP-6122-JH2B]
ConfigPath = "/NP-6122-JH2B/nkio_config.ini"
[NP-6122-JH3]
ConfigPath = "/NP-6122-JH3/nkio_config.ini"
[NP-6122-JH5]
ConfigPath = "/NP-6122-JH5/nkio_config.ini"
[NP-6123-16I16O]
ConfigPath = "/NP-6123-16I16O/nkio_config.ini"
[NP-6123-L4]
ConfigPath = "/NP-6123-L4/nkio_config.ini"
[NP-6123-MVS]
ConfigPath = "/NP-6123-MVS/nkio_config.ini"
[NP-6125-H1]
ConfigPath = "/NP-6125-H1/nkio_config.ini"
[NP-6125-H1-NEW]
ConfigPath = "/NP-6125-H1-NEW/nkio_config.ini"
[NP-6125-H1B]
ConfigPath = "/NP-6125-H1B/nkio_config.ini"
[NP-6125-H7-NEW]
ConfigPath = "/NP-6125-H7-NEW/nkio_config.ini"
[NP-6125-H7B]
ConfigPath = "/NP-6125-H7B/nkio_config.ini"
[NP-6125-JH2]
ConfigPath = "/NP-6125-JH2/nkio_config.ini"
[NP-6125-JH2-NEW]
ConfigPath = "/NP-6125-JH2-NEW/nkio_config.ini"
[NP-6125-JH2B]
ConfigPath = "/NP-6125-JH2B/nkio_config.ini"
[NP-6125-JH3]
ConfigPath = "/NP-6125-JH3/nkio_config.ini"
[NP-6125-JH5]
ConfigPath = "/NP-6125-JH5/nkio_config.ini"
[NP-6132-H1]
ConfigPath = "/NP-6132-H1/nkio_config.ini"
[NP-6132-H1-NEW]
ConfigPath = "/NP-6132-H1-NEW/nkio_config.ini"
[NP-6132-H1B]
ConfigPath = "/NP-6132-H1B/nkio_config.ini"
[NP-6132-H7-NEW]
ConfigPath = "/NP-6132-H7-NEW/nkio_config.ini"
[NP-6132-H7B]
ConfigPath = "/NP-6132-H7B/nkio_config.ini"
[NP-6132-JH2]
ConfigPath = "/NP-6132-JH2/nkio_config.ini"
[NP-6132-JH2-NEW]
ConfigPath = "/NP-6132-JH2-NEW/nkio_config.ini"
[NP-6132-JH2B]
ConfigPath = "/NP-6132-JH2B/nkio_config.ini"
[NP-6132-JH3]
ConfigPath = "/NP-6132-JH3/nkio_config.ini"
[NP-6132-JH5]
ConfigPath = "/NP-6132-JH5/nkio_config.ini"
[NP-6133-16I16O]
ConfigPath = "/NP-6133-16I16O/nkio_config.ini"
[NP-6133-L4]
ConfigPath = "/NP-6133-L4/nkio_config.ini"
[NP-6133-MVS]
ConfigPath = "/NP-6133-MVS/nkio_config.ini"
[NP-6135-H1]
ConfigPath = "/NP-6135-H1/nkio_config.ini"
[NP-6135-H1-NEW]
ConfigPath = "/NP-6135-H1-NEW/nkio_config.ini"
[NP-6135-H1B]
ConfigPath = "/NP-6135-H1B/nkio_config.ini"
[NP-6135-H7-NEW]
ConfigPath = "/NP-6135-H7-NEW/nkio_config.ini"
[NP-6135-H7B]
ConfigPath = "/NP-6135-H7B/nkio_config.ini"
[NP-6135-JH2]
ConfigPath = "/NP-6135-JH2/nkio_config.ini"
[NP-6135-JH2-NEW]
ConfigPath = "/NP-6135-JH2-NEW/nkio_config.ini"
[NP-6135-JH2B]
ConfigPath = "/NP-6135-JH2B/nkio_config.ini"
[NP-6135-JH3]
ConfigPath = "/NP-6135-JH3/nkio_config.ini"
[NP-6135-JH5]
ConfigPath = "/NP-6135-JH5/nkio_config.ini"
[XXX4]
ConfigPath = "/XXX4/nkio_config.ini"
[NK3310_RISER_SM8I8O]
ConfigPath = "/NK3310_RISER_SM8I8O/nkio_config.ini"
[AC-1121]
ConfigPath = "/AC-1121/nkio_config.ini"
[NP-61x0-16I16O]
ConfigPath = "/NP-61x0-16I16O/nkio_config.ini"
[NP-61x0-EX01]
ConfigPath = "/NP-61x0-EX01/nkio_config.ini"
[NP-61x0-MVS]
ConfigPath = "/NP-61x0-MVS/nkio_config.ini"
#


